version: '3.1'

services:
  db:
    image: postgres
  web:
    build: ./config
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ../backoffice:/backoffice
    ports:
      - "8081:8000"
    depends_on:
      - db